name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "42c2b561-c1d9-46d4-961e-478c889b16f3"      # 替换为你创建的数据库 ID
